version: '3'

services:
  nginx:
    image: nginx:1-alpine
    depends_on:
      - aqua
      - beige
    ports:
      - 5000:3000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

  aqua:
    image: node:16-alpine
    command: npm run dev
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
      PORT: 8080
    ports:
      - 5001:8080
    volumes:
      - ./aqua:/app
    working_dir: /app

  beige:
    image: node:16-alpine
    command: npm run dev
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
      PORT: 8080
    ports:
      - 5002:8080
    volumes:
      - ./beige:/app
    working_dir: /app


  # blue:
  #   image: node:16-alpine
  #   command: npm run serve
  #   environment:
  #     HOST: 0.0.0.0
  #     NODE_ENV: development
  #     PORT: 8080
  #   ports:
  #     - 5002:8080
  #   volumes:
  #     - ./blue:/app
  #   working_dir: /app

  # red:
  #   image: node:16-alpine
  #   command: npm run serve
  #   environment:
  #     HOST: 0.0.0.0
  #     NODE_ENV: development
  #     PORT: 8080
  #   ports:
  #     - 5003:8080
  #   volumes:
  #     - ./red:/app
  #   working_dir: /app
